// Code generated by cmd/anchorgen. DO NOT EDIT.
// Source: anchors.yaml — re-run `go generate ./internal/trustanchor`
// to regenerate after editing the YAML descriptor.

package trustanchor

import "time"

var embedded = []Anchor{
	{
		Name:       "dev-desertbread-ca-2026-04-20",
		Issuer:     "dev-desertbread-ca-2026-04-20",
		PublicKey:  []byte{0xb5, 0x2a, 0x46, 0xfa, 0xc5, 0xdf, 0x52, 0x9e, 0x60, 0x86, 0xa4, 0x3b, 0xe5, 0xb0, 0xf8, 0x96, 0x32, 0x2f, 0xc1, 0xc9, 0x4f, 0x43, 0x40, 0x13, 0x75, 0x82, 0x03, 0x6c, 0xd9, 0xd1, 0x8c, 0x25},
		ValidFrom:  time.Date(2026, 4, 20, 0, 0, 0, 0, time.UTC),
		ValidUntil: time.Date(2027, 4, 20, 0, 0, 0, 0, time.UTC),
	},
}
